[app]

# (str) Title of your application
title = AghaKocholo Scanner

# (str) Package name
package.name = aghakocholoscanner

# (str) Package domain (needed for android packaging)
package.domain = org.aghakocholo

# (str) Source files where the include_exts is located
source.dir = .

# (list) Source files to include (let it empty to include all files)
source.include_exts = py,png,jpg,kv,atlas
